# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4185086456fd241a851cc5fedc163d3ac0361dfb88ea603cbd4f11a8bf052666d8d37a73643f975cd7c0985972f377a105ad5414764af3edc52b6b1d18a8ac30

test:
  secret_key_base: 739cbce467c31672460bd9aff5a8d8212d73f852a75c5d09b89eccf2037d2017d35432aae975715bac84a6603b897e2cd4b007a4db16b36dbfb6eabefe10bd23

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
